# Generated by Django 5.0.7 on 2024-08-06 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialGroupSidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام گروه شبکه های اجتماعی')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='EmailSidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='پست الکترونیکی')),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='BlogApp.socialgroupsidebar')),
            ],
            options={
                'verbose_name': 'ایمیل',
                'verbose_name_plural': 'ایمیل ها',
            },
        ),
        migrations.CreateModel(
            name='SocialSideBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام شبکه اجتماعی')),
                ('link', models.CharField(max_length=255, verbose_name='لینک شبکه اجتماعی')),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='BlogApp.socialgroupsidebar')),
            ],
            options={
                'verbose_name': 'ایمیل',
                'verbose_name_plural': 'ایمیل ها',
            },
        ),
    ]
