# Generated by Django 5.0.7 on 2024-08-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_socialgroupsidebar_emailsidebar_socialsidebar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialsidebar',
            options={'verbose_name': 'شبکه اجتماعی', 'verbose_name_plural': 'شبکه های اجتماعی'},
        ),
    ]
