# Generated by Django 5.0.7 on 2024-08-04 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Team', verbose_name='تصویر')),
                ('name', models.CharField(max_length=250, verbose_name='نام و نام خانوادگی')),
                ('subname', models.CharField(max_length=250, verbose_name='پوزیشن کاری')),
            ],
            options={
                'verbose_name': 'آواتار',
                'verbose_name_plural': 'آواتار ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='نام دسته بندی')),
                ('slug', models.CharField(max_length=220, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته بندی شغلی',
                'verbose_name_plural': 'دسته بندی های شغلی',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Team', verbose_name='تصویر')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('role', models.CharField(max_length=255, verbose_name='شغل')),
                ('category_slug', models.CharField(max_length=255)),
                ('fullImage', models.ImageField(blank=True, null=True, upload_to='Team', verbose_name='تصویر بزرک')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('signature', models.CharField(max_length=255, verbose_name='امضا')),
            ],
            options={
                'verbose_name': 'عضو',
                'verbose_name_plural': 'تیم',
            },
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=55, verbose_name='زیرنویس')),
                ('description', models.TextField(verbose_name='متن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Team', verbose_name='تصویر')),
                ('avatar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='TeamApp.avatar', verbose_name='آواتار')),
            ],
            options={
                'verbose_name': 'استخدام',
                'verbose_name_plural': 'استخدامی ها',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام شبکه اجتماعی')),
                ('link', models.CharField(max_length=255, verbose_name='لینک شبکه اجتماعی')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='TeamApp.team')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اطلاعات')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='TeamApp.team')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'اطلاعات',
            },
        ),
    ]
