# Generated by Django 5.0.7 on 2024-08-04 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام گروه')),
            ],
            options={
                'verbose_name': 'شرکت همکار',
                'verbose_name_plural': 'شرکت های همکار',
            },
        ),
        migrations.CreateModel(
            name='AllProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیرنویس')),
            ],
            options={
                'verbose_name': 'روند کاری',
                'verbose_name_plural': 'روند کاری',
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='متن سکشن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='About', verbose_name='تصویر سکشن')),
            ],
            options={
                'verbose_name': 'سکشن',
                'verbose_name_plural': 'جوایز',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name=' عنوان')),
                ('subtitle', models.CharField(max_length=200, verbose_name='زیر عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'اطلاعات شرکت',
                'verbose_name_plural': 'اطلاعات شرکت',
            },
        ),
        migrations.CreateModel(
            name='Company2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=50, verbose_name='زیرنویس')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'اطلاعات',
                'verbose_name_plural': 'اطلاعات بیشتر',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='پست الکترونیکی')),
                ('phone', models.CharField(max_length=12, verbose_name='تلفن')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'ارتباط با ما',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('subname', models.CharField(max_length=100, verbose_name='نوشتار دوم')),
                ('text', models.CharField(max_length=100, verbose_name='نوشتار امضا')),
            ],
            options={
                'verbose_name': 'امضا',
                'verbose_name_plural': 'امضاها',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=220, verbose_name='زیر عنوان')),
            ],
            options={
                'verbose_name': 'سکشن',
                'verbose_name_plural': 'رضایت مشتریان',
            },
        ),
        migrations.CreateModel(
            name='AwardItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان تقدیرنامه')),
                ('year', models.CharField(max_length=4, verbose_name='سال دریافت تقدیرنامه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='About', verbose_name='تصویر تقدیرنامه')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='AboutApp.award', verbose_name='جایزه')),
            ],
            options={
                'verbose_name': 'تقدیرنامه',
                'verbose_name_plural': 'تقدیرنامه ها',
            },
        ),
        migrations.CreateModel(
            name='Company2Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='About', verbose_name='تصویر')),
                ('company2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='AboutApp.company2')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='About', verbose_name='تصویر')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='AboutApp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='گروه روندی')),
                ('allProcess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='AboutApp.allprocess')),
            ],
            options={
                'verbose_name': 'گروه روندی',
                'verbose_name_plural': 'گروه های روندی',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='شرکت همکار')),
                ('image', models.ImageField(blank=True, null=True, upload_to='About')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner', to='AboutApp.aboutextra')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتم ها',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='توضیحات')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='AboutApp.group')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتم ها',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='توضیحات')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceItems', to='AboutApp.service')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتمها',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='signature',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to='AboutApp.signature', verbose_name=' امضا'),
        ),
        migrations.CreateModel(
            name='TestItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('image', models.ImageField(blank=True, null=True, upload_to='About', verbose_name='تصویر مشتری')),
                ('role', models.CharField(max_length=100, verbose_name='شغل مشتری')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('testimonial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testItems', to='AboutApp.testimonial')),
            ],
        ),
    ]
