# Generated by Django 5.0.7 on 2024-08-10 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیر عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Home', verbose_name='تصویر')),
                ('image_alt', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیرنویس')),
                ('description', models.TextField(verbose_name='متن')),
            ],
            options={
                'verbose_name': 'برتری',
                'verbose_name_plural': 'برتری ها',
            },
        ),
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='تصویر پس زمینه')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیرنویس')),
                ('description', models.TextField(verbose_name='متن')),
            ],
            options={
                'verbose_name': 'فلسفه ',
                'verbose_name_plural': 'فلسفه ما',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیر عنوان')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
        migrations.CreateModel(
            name='HowWeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیرنویس')),
            ],
            options={
                'verbose_name': 'روند ما',
                'verbose_name_plural': 'روند ما',
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیر عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'ایده',
                'verbose_name_plural': 'ایده ها',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=200, verbose_name='زیر عنوان')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس ها',
            },
        ),
        migrations.CreateModel(
            name='AboutItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار')),
                ('valueAfter', models.CharField(max_length=20, verbose_name='مقدار پسین')),
                ('label', models.CharField(max_length=255, verbose_name='لیبل')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutItems', to='HomeApp.about')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتم ها',
            },
        ),
        migrations.CreateModel(
            name='AdvantageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('our_advantages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantageItems', to='HomeApp.advantage')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتم ها',
            },
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Team', verbose_name='تصویر')),
                ('name', models.CharField(max_length=250, verbose_name='نام و نام خانوادگی')),
                ('subName', models.CharField(max_length=250, verbose_name='پوزیشن کاری')),
                ('about', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HomeApp.about')),
            ],
            options={
                'verbose_name': 'آواتار',
                'verbose_name_plural': 'آواتار ها',
            },
        ),
        migrations.CreateModel(
            name='CoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('our_core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coreItems', to='HomeApp.core')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتم ها',
            },
        ),
        migrations.CreateModel(
            name='HeroItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Home', verbose_name='اسلاید')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='HomeApp.hero')),
            ],
            options={
                'verbose_name': ' اسلاید',
                'verbose_name_plural': ' اسلاید ها',
            },
        ),
        migrations.CreateModel(
            name='IdeaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Icons', verbose_name='آیکئ')),
                ('label', models.CharField(max_length=255, verbose_name='لیبل')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideaItems', to='HomeApp.idea')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتم ها',
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Icons/', verbose_name='آیکن')),
                ('num', models.CharField(max_length=7, verbose_name='تعداد')),
                ('text', models.TextField(verbose_name='توضیحات')),
                ('what_we_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceItems', to='HomeApp.service')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتم ها',
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Icons', verbose_name='آیکن')),
                ('text', models.TextField(verbose_name='توضیحات')),
                ('how_we_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workItems', to='HomeApp.howwework')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتم ها',
            },
        ),
    ]
