# Generated by Django 5.0.7 on 2024-08-10 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='about',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='HomeApp.about'),
        ),
    ]
