# Generated by Django 5.0.7 on 2024-08-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeApp', '0002_alter_avatar_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image_alt',
        ),
    ]
