# Generated by Django 5.0.7 on 2024-08-08 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیر عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='Service', verbose_name='تصویر')),
                ('image_alt', models.CharField(max_length=255, verbose_name='نام عکس')),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='Service', verbose_name='آواتار')),
                ('avatar_name', models.CharField(max_length=255, verbose_name='نام آواتار')),
                ('avatar_subname', models.CharField(max_length=255, verbose_name='زیر نام آواتار')),
            ],
            options={
                'verbose_name': 'معرفی',
                'verbose_name_plural': 'معرفی ما',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.CharField(max_length=155, verbose_name='زیر عنوان')),
            ],
            options={
                'verbose_name': 'راه ارتباطی',
                'verbose_name_plural': 'راه های ارتباطی',
            },
        ),
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان ')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیرنویس')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی ها',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Icons')),
                ('short', models.TextField(verbose_name='توضیح کوتاه')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
            },
        ),
        migrations.CreateModel(
            name='SideBarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان زیر مجموعه ساید بار')),
            ],
            options={
                'verbose_name': 'سایدبار',
                'verbose_name_plural': 'سایدبار',
            },
        ),
        migrations.CreateModel(
            name='VisionsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان بخش ویژگی ها')),
                ('subtitle', models.CharField(max_length=255, verbose_name='زیرعنوان بخش ویژگی ها')),
            ],
            options={
                'verbose_name': 'اهداف ما',
                'verbose_name_plural': 'اهداف ما',
            },
        ),
        migrations.CreateModel(
            name='AboutList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=255, verbose_name='لیست')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutLists', to='ServiceApp.aboutsection')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'لیست پروموشن ها',
            },
        ),
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='ServiceApp.contact')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
            },
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='ServiceApp.contact')),
            ],
            options={
                'verbose_name': 'ایمیل',
                'verbose_name_plural': 'ایمیل ها',
            },
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='تلفن')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='ServiceApp.contact')),
            ],
            options={
                'verbose_name': 'تلفن',
                'verbose_name_plural': 'تلفن ها',
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='سوال')),
                ('content', models.TextField(verbose_name='جواب سوال')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqItems', to='ServiceApp.faqsection')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_item', models.CharField(max_length=255, verbose_name='آیتم های برجسته')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featureItems', to='ServiceApp.feature')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'لیست ویژگی ها',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Service', verbose_name='تصویر گالری')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ServiceApp.service')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'گالری',
            },
        ),
        migrations.CreateModel(
            name='DescriptionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='آیتم')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listItems', to='ServiceApp.service')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'برجستگی ها',
            },
        ),
        migrations.CreateModel(
            name='Description2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن')),
                ('title2', models.CharField(max_length=255, verbose_name='عنوانبخش مزایا اول')),
                ('body2', models.TextField(verbose_name='متن بخش مزایا اول')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions2', to='ServiceApp.service')),
            ],
            options={
                'verbose_name': 'نوشتار دوم',
                'verbose_name_plural': 'نوشتارهای بخش دوم',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن')),
                ('title2', models.CharField(max_length=255, verbose_name='عنوانبخش مزایا اول')),
                ('body2', models.TextField(verbose_name='متن بخش مزایا اول')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='ServiceApp.service')),
            ],
            options={
                'verbose_name': 'نوشتار',
                'verbose_name_plural': 'نوشتارها',
            },
        ),
        migrations.CreateModel(
            name='SideBarCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(blank=True, null=True, verbose_name='عنوان شمارنده')),
                ('counter', models.IntegerField(blank=True, default=0, null=True, verbose_name='شمارنده')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='ServiceApp.sidebaritem')),
            ],
        ),
        migrations.CreateModel(
            name='SideBarContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='ServiceApp.sidebaritem')),
            ],
        ),
        migrations.CreateModel(
            name='VisionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('icon', models.CharField(max_length=255, verbose_name='آیکون')),
                ('text', models.TextField(verbose_name='متن')),
                ('vision_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VItems', to='ServiceApp.visionssection')),
            ],
            options={
                'verbose_name': 'آیتم هدف',
                'verbose_name_plural': 'لیست اهداف',
            },
        ),
    ]
