# Generated by Django 5.0.7 on 2024-08-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visionitem',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='Icons', verbose_name='آیکون'),
        ),
    ]
