# Generated by Django 5.0.7 on 2024-08-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0003_sidebar_remove_sidebarcounter_item_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidebarcounter',
            options={'verbose_name': 'شمارنذه', 'verbose_name_plural': 'شمارنذه ها'},
        ),
        migrations.AlterField(
            model_name='sidebarcounter',
            name='label',
            field=models.CharField(default=1, max_length=255, verbose_name='عنوان شمارنده'),
            preserve_default=False,
        ),
    ]
