# Generated by Django 5.0.7 on 2024-08-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0004_alter_sidebarcounter_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebarcounter',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='sidebarcounter',
            name='label',
        ),
        migrations.AddField(
            model_name='sidebarcounter',
            name='counter1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='شمارنده اول'),
        ),
        migrations.AddField(
            model_name='sidebarcounter',
            name='counter2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='شمارنده دوم'),
        ),
        migrations.AddField(
            model_name='sidebarcounter',
            name='counter3',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='شمارنده سوم'),
        ),
        migrations.AddField(
            model_name='sidebarcounter',
            name='counter4',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='شمارنده چهارم'),
        ),
        migrations.AddField(
            model_name='sidebarcounter',
            name='label1',
            field=models.CharField(default=1, max_length=255, verbose_name='عنوان شمارنده اول'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidebarcounter',
            name='label2',
            field=models.CharField(default=1, max_length=255, verbose_name='عنوان شمارنده دوم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidebarcounter',
            name='label3',
            field=models.CharField(default=1, max_length=255, verbose_name='عنوان شمارنده سوم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidebarcounter',
            name='label4',
            field=models.CharField(default=1, max_length=255, verbose_name='عنوان شمارنده چهارم'),
            preserve_default=False,
        ),
    ]
