# Generated by Django 5.0.7 on 2024-08-09 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceApp', '0005_remove_sidebarcounter_counter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sidebar',
            options={'verbose_name': 'سایدبار مادر', 'verbose_name_plural': 'سایدبار مادر'},
        ),
    ]
