# Generated by Django 5.0.7 on 2024-08-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0002_alter_project_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
    ]
